### PR TITLE
[RFR] Change screens a little for a better visual

### PR DESCRIPTION
**Pull request by JulienMattiussi**
image

Only UI changes on this PR
(With a very little commit to fix app crash when opend for first time and no default page was define)

### CODE REVIEW

**Review by djhi — CHANGES_REQUESTED** [review]
You should distinguish the important buttons (new games) from the others. Maybe with a different color? Lighter blue ou grey for the less important ones ?

**Comment by djhi** [comment]
Also, can you rebase?

**Comment by JulienMattiussi** [comment]
By the way, I think most important buttons are not New games, even if it's the first stage for playing.
In think player should check his current games first, then opened game by others players
And start a new game only if he don't find existing games
But I not sure that changing buttons order or color  could be more friendly.
I try

**Comment by djhi** [comment]
At least separate them visually a little. There's one big blue square here

**Review by djhi — APPROVED** [review]

**Pull request merged**
